### ISSUE TITLE
How to display the file

### ISSUE THREAD

**Issue by PaheerathanSelvarasa** [vlaim/yii2-file-upload#1]
How to display the file uploaded to aws bucket in index?

**Comment by vlaim** [comment]
Hi, you can get the file path after upload as a property: 

`
$uploader = new FileUpload($storage, $storageAuthParams);
$url = $uploader->uploadFromFile($file)->path;
`

**Comment by PaheerathanSelvarasa** [comment]
@vlaim Thank you!

**Comment by PaheerathanSelvarasa** [comment]
Can I get pretty url from that?
